### ISSUE TITLE
When compiled with webpack the output file is 6 times larger

### ISSUE THREAD

**Issue by overtune** [Pikaday/Pikaday#483] opened 2016-02-10 15:25 UTC
I have a really weird problem.
I use webpack to compile a minified source of my javascript. But when running webpack (with the "UglifyJsPlugin" plugin) the compiled file of Pikaday weights 213kb (the source file is only 36kb).
So the "minified" file is about 6 times larger than the original.

Not really shure whats the source of the problem. Perhaps it's something in webpack?
But I thought I could at least ask here to see if you have come across something like this...

**Comment by ryanmargheriti** [comment] 2016-05-09 10:22
@overtune How are you importing it?

**Comment by overtune** [comment] 2016-05-19 08:59
It's imported with the define method (in an AMD-module).

**Comment by PhiLhoSoft** [comment] 2017-01-03 15:49
Perhaps Webpack picks the optional dependency, ie. Moment.js, which can be large with all its locale files.
In another project using Moment in Webpack, I have this in the list of plugins:

		// Reference: http://webpack.github.io/docs/list-of-plugins.html#ignoreplugin
		// Ignore some modules. Here, avoids loading all locales of Moment.js (rather big! reduces vendor file of 165 KB).
		// We can then require specific ones. See also http://stackoverflow.com/questions/25384360/how-to-prevent-moment-js-from-loading-locales-with-webpack
		new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),

**Comment by splintercode** [comment] 2017-02-18 00:43
I ran into this issue as well. The big problem is when using CLIs like Create React App or the Angular CLI you do not have access to the webpack config. I'm using this on the Angular CLI and moment and all the locales are pulled in even though I'm not using moment anywhere in my project.

**Comment by prkirby** [comment] 2017-10-19 16:52
Having this same issue, simply using `import pikaday from 'pikaday';`
Literally doubles my minified javascript haha.

**Comment by wojciechczerniak** [comment] 2018-10-30 13:46
Duplicate of #815

**Closed by wojciechczerniak** 2018-10-30 13:46 UTC
