### ISSUE TITLE
Define callbacks in attributes

### ISSUE THREAD

**Issue by michaelfreitag** [Pikaday/Pikaday#129] opened 2014-03-14 13:01 UTC
May be it is interesting in case of jquery plugin usage:

Snip line: 38-53 of pikaday.jquery.js

```
         if (!(plugin instanceof Pikaday)) {
                if (typeof args[0] === 'object') {
                    var options = $.extend({}, args[0]);
                    options.field = self[0];

                    if (self.data('pikadayOnSelect')) {
                        options.onSelect = new Function(self.data('pikadayOnSelect'));
                    }

                    self.data('pikaday', new Pikaday(options));
                }
            } else {
                if (typeof args[0] === 'string' && typeof plugin[args[0]] === 'function') {
                    plugin[args[0]].apply(plugin, Array.prototype.slice.call(args,1));
                }
            }
```

After that you can define the callback as html data attribute.

```
<input data-pikaday-on-select="updateNextInspection();" name="foo" type="text" value="">
```

**Comment by wojciechczerniak** [comment] 2018-10-30 21:13
Duplicate of #396

**Closed by wojciechczerniak** 2018-10-30 21:13 UTC
