### ISSUE TITLE
With RequireJS, optional momentjs dependency loads only sometimes.

### ISSUE THREAD

**Issue by luhn** [Pikaday/Pikaday#395] opened 2015-09-05 21:23 UTC
Optional dependencies aren't supported in RequireJS, so it looks like Pikaday gets around that by obfuscating the dependency from RequireJS and hoping that momentjs is loaded by the time Pikaday is initialized.  Since RequireJS is asynchronous, this occasionally fails.

There's [some discussion on Stackoverflow](http://stackoverflow.com/questions/14164610/requirejs-optional-dependency), but it doesn't look like there's a tidy way to implement an optional dependency.  Perhaps define two modules, `pikaday` w/o momentjs and `pikaday.moment` w/ momentjs?

**Comment by Jmeyering** [comment] 2015-09-17 03:04
This is breaking things for me also.

**Comment by fusioned** [comment] 2015-10-08 16:01
I concur that this is breaking using the standard RequireJS setup, however I try to delay loading of the pikaday module.  #409 fixed this.

**Comment by rikkert** [comment] 2015-11-13 12:41
At the time, I discussed this with @jrburke and the implementation is the only way to do this.
I can't remember having issues, although running r.js in production like this for a long time.
Are you using moment in your app code as well?

**Comment by Jmeyering** [comment] 2015-11-16 01:37
the issue that I ran into was that depending on unknown factors r.js would load moment above / below pikaday, because it is unable to read inline require() calls with a variable parameter.

Beacuse r.js cannot view it as a dependency, sometimes it loads after moment, which causes the formatting options to fail.

http://requirejs.org/docs/optimization.html

**Comment by jrburke** [comment] 2015-11-16 05:40
The define call could be set up like this:

```javascript
        define(function (req) {
            return factory(require('moment'));
        });
```

and then to instruct AMD users that did not want to use moment with this library to create a moment.js file in the baseUrl directory. That will result in the AMD loader loading the empty file, and returning `undefined` for the module value, which should then also work.

FWIW, something like this will be needed for ES2015 modules, as there are no optional dependencies in that model either.

**Comment by nathanboktae** [comment] 2015-11-16 22:46
Won't the `shim` API work for this situation?

```
require.config({
  shim: {
    pickaday: {
      deps: ['moment']
    }
  }
})
```

**Comment by jrburke** [comment] 2015-11-17 00:07
Since pickaday registers with modules APIs in its umd wrapper, shim should not be used.

**Comment by appeltaert** [comment] 2016-02-10 14:34
The workaround for the "optional dependency"(lol, I know it's a thing, but 101 how to break the semantic web) expects Moment.js to always be loaded before Pikaday is, I can repeat what OP already said but lets not..
Why does it support AMD at all then? Lets remove it and use a shim or even define our own module that injects Moment.js into Pikaday, or even allow it to be passed on construction level?
How is this a valid implementation if it actually breaks using Moment.js with RequireJS? The fact that it's optional says enough, let it be up to the user to use it and don't depend on it?

**Comment by Jmeyering** [comment] 2016-02-12 02:57
I actually things the proposed above is a very reasonable solution. If the maintainers truly want an "optional" dependency, then an AMD module should NOT be exposed as AMD modules don't support any "optional" dependencies.

**Comment by wojciechczerniak** [comment] 2018-10-30 13:40
Duplicate of #815

**Closed by wojciechczerniak** 2018-10-30 13:40 UTC
