### ISSUE TITLE
Moment import breaks webpack 4 production build

### ISSUE THREAD

**Issue by ThomasLabstep** [Pikaday/Pikaday#811] opened 2018-10-01 08:47 UTC
Hello,

We have a create-react-app with webpack 4 and babel 7.

Our production build has a warning that turns into an error:

```
./node_modules/handsontable/node_modules/pikaday/pikaday.js 29:17-24
Critical dependency: the request of a dependency is an expression
```

What is the right fix?

Thanks.

**Comment by Hinaser** [comment] 2018-10-02 04:13
Duplicate #518 

But I also come across the same issue.
I am using handsontable and pickaday in react and having trouble with this warning messages.

This is definitely temporary patch but I can suggest to directly edit code in `node_modules/pikaday/pikaday.js`  and
`node_modules/handsontable/dist/pikaday/pikaday.js`
or anywhere the problematic code resides .
if you want to suppress warning in React.

Before edit
```
    var moment;
    if (typeof exports === 'object') {
        // CommonJS module
        // Load moment.js as an optional dependency
        try { moment = require('moment'); } catch (e) {}
        module.exports = factory(moment);
    } else if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(function (req)
        {
            // Load moment.js as an optional dependency
            var id = 'moment';
            try { moment = req(id); } catch (e) {}
            return factory(moment);
        });
    } else {
        root.Pikaday = factory(root.moment);
    }
```

After edit
```
    var moment = require('moment');
    module.exports = factory(moment);
```

Of course this edit will be reset when you re-install npm packages.

**Comment by ThomasLabstep** [comment] 2018-10-02 07:13
Thanks that's a good hotfix. It means we can fork pickaday and target our repo in the package.json.

We decided to use the more violent webpack config parameter:
```
  module: {
    exprContextCritical: false,
    ...
```

**Comment by wojciechczerniak** [comment] 2018-10-30 13:52
Duplicate of #815

**Closed by wojciechczerniak** 2018-10-30 13:52 UTC
