### ISSUE TITLE
Is it possible to set different formats?

### ISSUE THREAD

**Issue by ersanceylan** [Pikaday/Pikaday#591] opened 2016-10-05 13:46 UTC
I wonder if it is possible to set different formats for shown value and posted value without manipulating form submit event.

For example;
I want users to see datepicker format as `MMM dd, YYYY`
but I also sent date input formatted as `YYYY-MM-DD`

**Comment by trodicaro** [comment] 2017-01-09 19:27
We are using Pikaday at my job and we'd benefit from a similar formatting (in our case render on page American date and send behind the scenes as ISO 8601: render 01/09/2017 vs send 2017/01/09.

**Comment by dave1010** [comment] 2017-11-15 16:01
Dupe of #452 ?

**Comment by wojciechczerniak** [comment] 2018-10-30 10:41
Duplicate of #452. Thanks @dave1010

**Closed by wojciechczerniak** 2018-10-30 10:41 UTC
