### ISSUE TITLE
Scroll on touch closes datepicker

### ISSUE THREAD

**Issue by linnett** [Pikaday/Pikaday#584] opened 2016-09-26 10:04 UTC
If I open the datepicker on a touch device and then try and scroll over the calendar, it selects the date rather than allowing the scroll. I would expect the date to be selected on click but when the user is scrolling over the datepicker, it should not disappear.

**Comment by wojciechczerniak** [comment] 2018-11-02 15:03
Linked PR #397

**Comment by wojciechczerniak** [comment] 2018-11-02 15:05
Actually this is a duplicate of  #569

**Closed by wojciechczerniak** 2018-11-02 15:05 UTC
