### ISSUE TITLE
Time as well as date

### ISSUE THREAD

**Issue by LiamDawe** [Pikaday/Pikaday#487] opened 2016-02-14 17:00 UTC
Just curious, is there/will there ever be a way to include time as well?

**Comment by owenmead** [comment] 2016-02-15 20:20
https://github.com/owenmead/Pikaday

**Comment by owenmead** [comment] 2016-02-15 20:24
Most people don't need time, so a separate fork is maintained.

**Comment by NaughtySquid** [comment] 2016-02-16 20:22
Thanks, using it now works great!

**Comment by wojciechczerniak** [comment] 2018-10-29 08:52
Duplicate of #191

**Closed by wojciechczerniak** 2018-10-29 08:52 UTC
