### ISSUE TITLE
Pikaday - Having issues changing the default properties of i18n. 

### ISSUE THREAD

**Issue by maximus-lynn** [Pikaday/Pikaday#657] opened 2017-03-03 16:44 UTC
I've made a stackoverflow question regarding this so please relate to it. 

http://stackoverflow.com/questions/42583829/pikaday-trying-to-figure-out-why-im-getting-an-area-when-trying-to-set-my-own

However I want to point out that I am also using this version: "^1.5.1"

Please let me know if you know what I am doing wrong. 

I am also init the function like this: 
class Main {
    // Specific to Fellow Application
    InitFellowApplication() {
        fellowApplication.init()
    }

    // Specfic to Edit Profile
    InitShowAddress() {
        showAddress.init()
    }

    InitDashboard() {
        dashboard.init()
    }

    globalScripts() {
        InputChecker.init()
        datePicker.init()
        selectTag.init()
    }
}

export let main = new Main()
main.globalScripts()

Many thanks

**Comment by wojciechczerniak** [comment] 2018-11-02 14:55
There is an issue #663 that says if you start to define `i18n` you have to provide all properties. You get `Cannot read property '0' of undefined` probably because Pikaday can't read weekdays array.

Closing as duplicate of #663

**Closed by wojciechczerniak** 2018-11-02 14:55 UTC
