### ISSUE TITLE
Disabled dates still accessible using keyboard or manually entered dates

### ISSUE THREAD

**Issue by davedawson** [Pikaday/Pikaday#582] opened 2016-09-21 18:35 UTC
I'm using the `disableWeekends` option, and it works great on mouse click. But when using the keyboard to navigate dates, users are still able to select those disabled dates. This is also an issue when manually entering a disabled date in the text field.

**Comment by wojciechczerniak** [comment] 2019-03-12 13:27
Duplicate of #723

**Closed by wojciechczerniak** 2019-03-12 13:27 UTC
