### ISSUE TITLE
"Next month" jumps two months in Android 4.4.2

### ISSUE THREAD

**Issue by MikaelEdebro** [Pikaday/Pikaday#540] opened 2016-06-13 09:33 UTC
First off, thanks for a great plugin. However, we're having an issue that might have quite large implications for mobile users.

When pressing "Next month" icon on my Samsung Note 2 (Android 4.4.2 native browser), it jumps two months, thus making it impossible to select a date that is in the month between.

Could the issue be that it's triggering both for "touchdown" and "touchup" (not sure what the events are actually called in the mobile world)?
It seems to be working fine when you hold down for a second or more. But if you just tap, it will jump 2 months.

I tried adding a debounce method, like this, but unfortunately it didn't resolve the issue:

```
picker = new Pikaday({
    field: document.getElementById(scope.id),
    defaultDate: new Date(scope.model),
    setDefaultDate: true,
    minDate: new Date(scope.minDate),
    maxDate: new Date(scope.maxDate),
    firstDay: 1,
    format: 'YYYY-MM-DD',
    i18n: getLocalizedNames(),
    numberOfMonths: getMonthsToShow(),   // 1 month for mobile, 2 for other devices
    position: datepickerPosition,
    reposition: false
});

picker._onMouseDown = debounce(picker._onMouseDown, 300);
```

It's working fine in Chrome for the same device. Only the native browser is having issues.
Any thoughts on potential solutions?

**Comment by takebo** [comment] 2016-07-13 17:38
Having same issue on native browser, Samsung Galaxy Tab 2 10.1, Android 4.0.3.

**Comment by wojciechczerniak** [comment] 2018-11-04 10:07
Duplicate of #569

**Closed by wojciechczerniak** 2018-11-04 10:07 UTC
