### ISSUE TITLE
Produce a Month and Year only date picker

### ISSUE THREAD

**Issue by rlebowitz** [Pikaday/Pikaday#708] opened 2017-08-09 21:03 UTC
I am trying to use Pikaday to select months and years (no day).

I figured out that I can hide the calendar portion of the picker so that only the title portion of the picker appears with this CSS

.month-year .pika-table {
    display: none !important;
}

var observable.picker = new Pikaday({
                field: element,
                theme: 'month-year',
                format: format,
                inputFormats: inputFormats,
                clearInvalidInput: true,
                minDate: minDate.isValid() ? minDate.toDate() : undefined,
                maxDate: maxDate.isValid() ? maxDate.toDate() : undefined,
                onSelect: function(date) { observable(date); },
                onClear: function() { observable(null); },
                onClose: function() {
                    const d = new Date(observable.picker.calendars[0].year, observable.picker.calendars[0].month, 1);
                    observable(d);
                    observable.picker.setDate(d);
                }
        });

Unfortunately, when the calendar table is hidden, there is no way to initiate the onSelect function.  The one way to save the currently displayed month and year in the field is to initiate a blur event by clicking outside the element where the value is displayed.  This isn't exactly a great solution, I'd prefer to be able to replace the calendar table <div> with a <div> containing a button which will fire a blur event on the input element and close the picker.

Likewise, it'd be nice if I could capture the onPrev and onNext events to update the element value as the months and years change in the picker.

I've experimented heavily with the code, but the only way I see to make this work would be to modify the Pikaday source, which I'd prefer not to do if possible.  I tried to see if I could override functions within the code, etc.  none of which really worked.

Does anyone have a suggestion on a better way to achieve a month and year only picker using Pikaday?

Rob

**Comment by hectorlorenzo** [comment] 2017-10-09 14:31
I had to do the same and it required quite a lot of source code tinkering. If you want something simpler (and a little bit hacky), you could try to use the onDraw callback. Every time that you select a different month or year, the onDraw function triggers, so you could use it to fetch the value of the dropdowns straight away.

**Comment by wojciechczerniak** [comment] 2019-03-12 13:06
Duplicate of #562

**Closed by wojciechczerniak** 2019-03-12 13:06 UTC
