### ISSUE TITLE
moment.js vs browserify

### ISSUE THREAD

**Issue by rlidwka** [Pikaday/Pikaday#600] opened 2016-10-31 12:51 UTC
I'm trying to compile pikaday using browserify. If I do have moment.js installed, it gets bundled with pikaday (which makes client-side code unnecessarily large).

If I do not have moment.js installed, it throws:

```js
$ browserify ./pikaday.js 
Error: Cannot find module 'moment' from '/tmp/Pikaday'
    at /tmp/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
```

Here is a possible fix for it:

```js
--- a/pikaday.js
+++ b/pikaday.js
@@ -12,7 +12,8 @@
     if (typeof exports === 'object') {
         // CommonJS module
         // Load moment.js as an optional dependency
-        try { moment = require('moment'); } catch (e) {}
+        var _require = require;
+        try { moment = _require('moment'); } catch (e) {}
         module.exports = factory(moment);
     } else if (typeof define === 'function' && define.amd) {
         // AMD. Register as an anonymous module.
```

Javascript code works exactly the same, but this way the code doesn't have `require('moment')` in it, which won't trigger bundling.

Here's a relevant issue in browserify: https://github.com/substack/node-browserify/issues/653

**Comment by wojciechczerniak** [comment] 2018-10-30 13:38
Duplicate of #815

**Closed by wojciechczerniak** 2018-10-30 13:38 UTC
