### ISSUE TITLE
week number

### ISSUE THREAD

**Issue by seeley60** [Pikaday/Pikaday#512] opened 2016-04-29 17:28 UTC
Here in Switzerland if I display week number I have "18" for today (2016.04.29) but moment display "17" for the same day.

For us "17" is correct.

**Comment by andrei-sheina** [comment] 2016-05-03 12:18
Have the exact same issue. Option showWeekNumber show weeknumber + 1

**Comment by Electrofenster** [comment] 2016-05-04 07:53
@andrei-sheina how do you solved it?

**Comment by seeley60** [comment] 2016-05-04 08:04
I follow this :

https://github.com/dbushell/Pikaday/pull/443/commits/37478ffd8e6117fb3b81c74d1ee87c38e89252e4

and it works :-)

Jacques Bourquin

Chemin de la Maison Blanche 33
CH-2533 Evilard


Le 4 mai 2016 à 09:53:34, Lars (notifications@github.com) a écrit:

@andrei-sheina how do you solved it?

**Comment by wojciechczerniak** [comment] 2018-11-04 10:00
Duplicate of #388

**Closed by wojciechczerniak** 2018-11-04 10:00 UTC
