### ISSUE TITLE
Dynamic minDate/maxDate?

### ISSUE THREAD

**Issue by campbeln** [Pikaday/Pikaday#676] opened 2017-04-20 18:06 UTC
Currently, `minDate`/`maxDate` are expected to be dates. The expected type could be expanded to include a caller-defined function to calculate the min/max as required.

This would allow linked datepickers where one selects the min while the other selects the max date while communicating to the other seamlessly.

This could be accomplished with some simple code...

`localMinDate = (Object.prototype.toString.call(options.minDate) === '[object Function]' ? options.minDate() : options.minDate);`

`format` could benefit from a similar approach, allowing devs to avoid moment.js thanks to their own static formatter.

**Comment by wojciechczerniak** [comment] 2018-11-04 10:10
Duplicate of #165

**Closed by wojciechczerniak** 2018-11-04 10:10 UTC
