### ISSUE TITLE
Question: Is there a time picker feature available on pikaday?

### ISSUE THREAD

**Issue by ivanasetiawan** [Pikaday/Pikaday#633] opened 2017-01-24 12:02 UTC
I need a datepicker with a time picker functionality. Would pikaday be a good option for me?
I don't see any time picker feature, but are you planning to release something like that soon?

Thanks in advance!

**Comment by owenmead** [comment] 2017-01-25 05:24
https://github.com/owenmead/Pikaday

**Comment by wojciechczerniak** [comment] 2018-10-29 08:52
Duplicate of #191

**Closed by wojciechczerniak** 2018-10-29 08:52 UTC
